AWSTemplateFormatVersion: '2010-09-09'
Description: DynamoDB table to store exercise documents (schemaless except for partition key)

Parameters:
  TableName:
    Type: String
    Default: Exercises
    Description: Name of the DynamoDB table
  BillingMode:
    Type: String
    AllowedValues: [PROVISIONED, PAY_PER_REQUEST]
    Default: PAY_PER_REQUEST
    Description: Billing mode for the table
PointInTimeRecoverySpecification:
  PointInTimeRecoveryEnabled: true

Resources:
  ExercisesTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Ref TableName
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
      KeySchema:
        - AttributeName: id
          KeyType: HASH
      BillingMode: !Ref BillingMode
      SSESpecification:
        SSEEnabled: true
      PointInTimeRecoverySpecification:
        PointInTimeRecoveryEnabled: !Ref PointInTimeRecoveryEnabled

Outputs:
  TableName:
    Description: DynamoDB table name
    Value: !Ref ExercisesTable
    Export:
      Name: !Sub "${AWS::StackName}-ExercisesTableName"
  TableArn:
    Description: DynamoDB table ARN
    Value: !GetAtt ExercisesTable.Arn
    Export:
      Name: !Sub "${AWS::StackName}-ExercisesTableArn" 