AWSTemplateFormatVersion: '2010-09-09'
Description: Root stack that provisions the Exercises DynamoDB table and an IAM role with access

Parameters:
  StackNamePrefix:
    Type: String
    Default: Exercises
    Description: Prefix used to name stacks and resources
  ArtifactsBucketName:
    Type: String
    Description: Name of the S3 bucket that contains the nested templates under cloudformation/
  TableBillingMode:
    Type: String
    AllowedValues: [PROVISIONED, PAY_PER_REQUEST]
    Default: PAY_PER_REQUEST

Resources:
  DynamoDBNested:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub [
        "https://s3.amazonaws.com/${Bucket}/cloudformation/exercises.yaml",
        { Bucket: !Ref ArtifactsBucketName }
      ]
      Parameters:
        TableName: !Sub "${StackNamePrefix}Table"
        BillingMode: !Ref TableBillingMode

  IAMNested:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub [
        "https://s3.amazonaws.com/${Bucket}/cloudformation/iam-exercises-access.yaml",
        { Bucket: !Ref ArtifactsBucketName }
      ]
      Parameters:
        ExercisesTableArn: !GetAtt DynamoDBNested.Outputs.TableArn
        RoleName: !Sub "${StackNamePrefix}AppRole"
    DependsOn:
      - DynamoDBNested

Outputs:
  TableName:
    Description: DynamoDB table name
    Value: !GetAtt DynamoDBNested.Outputs.TableName
  TableArn:
    Description: DynamoDB table ARN
    Value: !GetAtt DynamoDBNested.Outputs.TableArn
  AppRoleArn:
    Description: IAM role with table access
    Value: !GetAtt IAMNested.Outputs.RoleArn 